name: Build NeoKolors.Settings

on:
  push:
    paths:
      - 'NeoKolors.Settings/**'
      - 'NeoKolors.Settings.Tests/**'
      - '.github/workflows/build-settings.yml'

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest 

    env:
      SolutionName: NeoKolors.sln
      ProjectPath: NeoKolors.Settings\NeoKolors.Settings.csproj
      TestProjectPath: NeoKolors.Settings.Tests\NeoKolors.Settings.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Build Projects
      run: dotnet build ${{ env.ProjectPath }} --configuration ${{ matrix.configuration }}

    - name: Execute unit tests
      run: dotnet test ${{ env.TestProjectPath }} --no-restore

    - name: Restore the application
      run: dotnet restore ${{ env.SolutionName }}
